#!/bin/bash
dirname=$1
archname=$2
shift
shift
if [ -d $dirname ]
then :
else
mkdir $dirname
fi
if [ $# = 0 ]
then
	for file in $(find ~ -type f)
	do
	cp "$file" "$dirname"
	done
else
	for param in "$@"
	do
		for file in $(find ~ -name "*.${param}" -type f)
		do
		new_name="$file"
		new_name="${file////_}"
		cp "$file" "$dirname"/"$new_name"
		#echo "$new_name"
		done
	done
fi
tar -czf "${archname}.tar" "$dirname"

